# Site settings

title: William Ruzvidzo's website
description: >
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings

markdown: kramdown
theme: minima
permalink: /blog/:title/
baseurl: ""

port: 8000
