# Site settings

title: William Ruzvidzo's website
baseurl: '/WilliamRuz.github.io'

# Google Analytics
google_analytics: UA-112502014-1

# Build settings

markdown: kramdown
theme: minima
permalink: /blog/:title/
baseurl: ""

port: 8000
